---

- name: NodeJS | Install repo
  yum_repository:
    name: nodesource
    description: Node.js Packages for Enterprise Linux 7 - $basearch
    baseurl: https://rpm.nodesource.com/pub_10.x/el/7/$basearch
    gpgcheck: yes
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    enabled: yes
  become: yes
  become_user: root

- name: NodeJS | Install package
  yum:
    name: nodejs
    update_cache: yes
  become: yes
  become_user: root
